version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  felicette1963:
    build: .
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=Felicette.flyio.com
      - VIRTUAL_PORT=80
    deploy:
      mode: replicated
      replicas: 2  # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.06'
          memory: 60M
        reservations:
          cpus: '0.02'
          memory: 20M
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first