# fly.toml app configuration file generated for felicette1963 on 2023-10-23T14:02:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "felicette1963"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]
